# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comm_window.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Comm_Window(object):
    def setupUi(self, Comm_Window):
        Comm_Window.setObjectName(_fromUtf8("Comm_Window"))
        Comm_Window.resize(991, 824)
        self.centralWidget = QtGui.QWidget(Comm_Window)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 8, 961, 741))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.Comm_Console = QtGui.QVBoxLayout(self.layoutWidget)
        self.Comm_Console.setMargin(11)
        self.Comm_Console.setSpacing(6)
        self.Comm_Console.setObjectName(_fromUtf8("Comm_Console"))
        self.TitleandSerialLayout = QtGui.QVBoxLayout()
        self.TitleandSerialLayout.setMargin(11)
        self.TitleandSerialLayout.setSpacing(6)
        self.TitleandSerialLayout.setObjectName(_fromUtf8("TitleandSerialLayout"))
        self.WheelBotComm = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.WheelBotComm.setFont(font)
        self.WheelBotComm.setAlignment(QtCore.Qt.AlignCenter)
        self.WheelBotComm.setObjectName(_fromUtf8("WheelBotComm"))
        self.TitleandSerialLayout.addWidget(self.WheelBotComm)
        self.Serial_Layout = QtGui.QHBoxLayout()
        self.Serial_Layout.setMargin(11)
        self.Serial_Layout.setSpacing(9)
        self.Serial_Layout.setObjectName(_fromUtf8("Serial_Layout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.Serial_Layout.addWidget(self.label)
        self.PortcomboBox = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PortcomboBox.sizePolicy().hasHeightForWidth())
        self.PortcomboBox.setSizePolicy(sizePolicy)
        self.PortcomboBox.setObjectName(_fromUtf8("PortcomboBox"))
        self.Serial_Layout.addWidget(self.PortcomboBox)
        self.Connect_Btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connect_Btn.sizePolicy().hasHeightForWidth())
        self.Connect_Btn.setSizePolicy(sizePolicy)
        self.Connect_Btn.setObjectName(_fromUtf8("Connect_Btn"))
        self.Serial_Layout.addWidget(self.Connect_Btn)
        self.Disconnect_Btn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disconnect_Btn.sizePolicy().hasHeightForWidth())
        self.Disconnect_Btn.setSizePolicy(sizePolicy)
        self.Disconnect_Btn.setObjectName(_fromUtf8("Disconnect_Btn"))
        self.Serial_Layout.addWidget(self.Disconnect_Btn)
        self.TitleandSerialLayout.addLayout(self.Serial_Layout)
        self.TitleandSerialLayout.setStretch(0, 2)
        self.TitleandSerialLayout.setStretch(1, 1)
        self.Comm_Console.addLayout(self.TitleandSerialLayout)
        self.Lo_Plots = QtGui.QHBoxLayout()
        self.Lo_Plots.setMargin(11)
        self.Lo_Plots.setSpacing(6)
        self.Lo_Plots.setObjectName(_fromUtf8("Lo_Plots"))
        self.Comm_Console.addLayout(self.Lo_Plots)
        self.ControlsandData = QtGui.QHBoxLayout()
        self.ControlsandData.setMargin(11)
        self.ControlsandData.setSpacing(6)
        self.ControlsandData.setObjectName(_fromUtf8("ControlsandData"))
        self.GainsPanel = QtGui.QVBoxLayout()
        self.GainsPanel.setMargin(11)
        self.GainsPanel.setSpacing(6)
        self.GainsPanel.setObjectName(_fromUtf8("GainsPanel"))
        self.Headin_Plt = QtGui.QLabel(self.layoutWidget)
        self.Headin_Plt.setObjectName(_fromUtf8("Headin_Plt"))
        self.GainsPanel.addWidget(self.Headin_Plt)
        self.GainTtl_SndCmd_lo = QtGui.QHBoxLayout()
        self.GainTtl_SndCmd_lo.setMargin(11)
        self.GainTtl_SndCmd_lo.setSpacing(6)
        self.GainTtl_SndCmd_lo.setObjectName(_fromUtf8("GainTtl_SndCmd_lo"))
        self.PId_Loop_Gain = QtGui.QLabel(self.layoutWidget)
        self.PId_Loop_Gain.setAlignment(QtCore.Qt.AlignCenter)
        self.PId_Loop_Gain.setObjectName(_fromUtf8("PId_Loop_Gain"))
        self.GainTtl_SndCmd_lo.addWidget(self.PId_Loop_Gain)
        self.SendCmds_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.SendCmds_checkBox.setObjectName(_fromUtf8("SendCmds_checkBox"))
        self.GainTtl_SndCmd_lo.addWidget(self.SendCmds_checkBox)
        self.GainsPanel.addLayout(self.GainTtl_SndCmd_lo)
        self.K_pLayout = QtGui.QHBoxLayout()
        self.K_pLayout.setMargin(11)
        self.K_pLayout.setSpacing(6)
        self.K_pLayout.setObjectName(_fromUtf8("K_pLayout"))
        self.K_plabel = QtGui.QLabel(self.layoutWidget)
        self.K_plabel.setObjectName(_fromUtf8("K_plabel"))
        self.K_pLayout.addWidget(self.K_plabel)
        self.K_pSlider = QtGui.QSlider(self.layoutWidget)
        self.K_pSlider.setOrientation(QtCore.Qt.Horizontal)
        self.K_pSlider.setObjectName(_fromUtf8("K_pSlider"))
        self.K_pLayout.addWidget(self.K_pSlider)
        self.kp_val = QtGui.QLabel(self.layoutWidget)
        self.kp_val.setObjectName(_fromUtf8("kp_val"))
        self.K_pLayout.addWidget(self.kp_val)
        self.GainsPanel.addLayout(self.K_pLayout)
        self.K_iLayout = QtGui.QHBoxLayout()
        self.K_iLayout.setMargin(11)
        self.K_iLayout.setSpacing(6)
        self.K_iLayout.setObjectName(_fromUtf8("K_iLayout"))
        self.K_iLabel = QtGui.QLabel(self.layoutWidget)
        self.K_iLabel.setObjectName(_fromUtf8("K_iLabel"))
        self.K_iLayout.addWidget(self.K_iLabel)
        self.K_iSlider = QtGui.QSlider(self.layoutWidget)
        self.K_iSlider.setOrientation(QtCore.Qt.Horizontal)
        self.K_iSlider.setObjectName(_fromUtf8("K_iSlider"))
        self.K_iLayout.addWidget(self.K_iSlider)
        self.ki_val = QtGui.QLabel(self.layoutWidget)
        self.ki_val.setObjectName(_fromUtf8("ki_val"))
        self.K_iLayout.addWidget(self.ki_val)
        self.GainsPanel.addLayout(self.K_iLayout)
        self.K_dLayout = QtGui.QHBoxLayout()
        self.K_dLayout.setMargin(11)
        self.K_dLayout.setSpacing(6)
        self.K_dLayout.setObjectName(_fromUtf8("K_dLayout"))
        self.K_dLabel = QtGui.QLabel(self.layoutWidget)
        self.K_dLabel.setObjectName(_fromUtf8("K_dLabel"))
        self.K_dLayout.addWidget(self.K_dLabel)
        self.K_dSlider = QtGui.QSlider(self.layoutWidget)
        self.K_dSlider.setOrientation(QtCore.Qt.Horizontal)
        self.K_dSlider.setObjectName(_fromUtf8("K_dSlider"))
        self.K_dLayout.addWidget(self.K_dSlider)
        self.kd_val = QtGui.QLabel(self.layoutWidget)
        self.kd_val.setObjectName(_fromUtf8("kd_val"))
        self.K_dLayout.addWidget(self.kd_val)
        self.GainsPanel.addLayout(self.K_dLayout)
        self.ControlsandData.addLayout(self.GainsPanel)
        self.MotSpd_DatLayout = QtGui.QVBoxLayout()
        self.MotSpd_DatLayout.setMargin(11)
        self.MotSpd_DatLayout.setSpacing(6)
        self.MotSpd_DatLayout.setObjectName(_fromUtf8("MotSpd_DatLayout"))
        self.Rotat_PWM = QtGui.QLabel(self.layoutWidget)
        self.Rotat_PWM.setObjectName(_fromUtf8("Rotat_PWM"))
        self.MotSpd_DatLayout.addWidget(self.Rotat_PWM)
        self.Motor_Speed = QtGui.QLabel(self.layoutWidget)
        self.Motor_Speed.setAlignment(QtCore.Qt.AlignCenter)
        self.Motor_Speed.setObjectName(_fromUtf8("Motor_Speed"))
        self.MotSpd_DatLayout.addWidget(self.Motor_Speed)
        self.MotorSpdLayout = QtGui.QHBoxLayout()
        self.MotorSpdLayout.setMargin(11)
        self.MotorSpdLayout.setSpacing(6)
        self.MotorSpdLayout.setObjectName(_fromUtf8("MotorSpdLayout"))
        self.LMotLbl = QtGui.QLabel(self.layoutWidget)
        self.LMotLbl.setObjectName(_fromUtf8("LMotLbl"))
        self.MotorSpdLayout.addWidget(self.LMotLbl)
        self.Lft_Motor_Speed = QtGui.QLabel(self.layoutWidget)
        self.Lft_Motor_Speed.setObjectName(_fromUtf8("Lft_Motor_Speed"))
        self.MotorSpdLayout.addWidget(self.Lft_Motor_Speed)
        self.RMotLbl = QtGui.QLabel(self.layoutWidget)
        self.RMotLbl.setObjectName(_fromUtf8("RMotLbl"))
        self.MotorSpdLayout.addWidget(self.RMotLbl)
        self.Rgt_Motor_Speed = QtGui.QLabel(self.layoutWidget)
        self.Rgt_Motor_Speed.setObjectName(_fromUtf8("Rgt_Motor_Speed"))
        self.MotorSpdLayout.addWidget(self.Rgt_Motor_Speed)
        self.MotSpd_DatLayout.addLayout(self.MotorSpdLayout)
        self.Load_Data = QtGui.QLabel(self.layoutWidget)
        self.Load_Data.setObjectName(_fromUtf8("Load_Data"))
        self.MotSpd_DatLayout.addWidget(self.Load_Data)
        self.LoadDat_Layout = QtGui.QHBoxLayout()
        self.LoadDat_Layout.setMargin(11)
        self.LoadDat_Layout.setSpacing(6)
        self.LoadDat_Layout.setObjectName(_fromUtf8("LoadDat_Layout"))
        self.LoadLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.LoadLineEdit.setObjectName(_fromUtf8("LoadLineEdit"))
        self.LoadDat_Layout.addWidget(self.LoadLineEdit)
        self.Load_Btn = QtGui.QPushButton(self.layoutWidget)
        self.Load_Btn.setObjectName(_fromUtf8("Load_Btn"))
        self.LoadDat_Layout.addWidget(self.Load_Btn)
        self.MotSpd_DatLayout.addLayout(self.LoadDat_Layout)
        self.RcdandPlybckLo = QtGui.QHBoxLayout()
        self.RcdandPlybckLo.setMargin(11)
        self.RcdandPlybckLo.setSpacing(6)
        self.RcdandPlybckLo.setObjectName(_fromUtf8("RcdandPlybckLo"))
        self.Record_Btn = QtGui.QPushButton(self.layoutWidget)
        self.Record_Btn.setObjectName(_fromUtf8("Record_Btn"))
        self.RcdandPlybckLo.addWidget(self.Record_Btn)
        self.Playback_Btn = QtGui.QPushButton(self.layoutWidget)
        self.Playback_Btn.setObjectName(_fromUtf8("Playback_Btn"))
        self.RcdandPlybckLo.addWidget(self.Playback_Btn)
        self.MotSpd_DatLayout.addLayout(self.RcdandPlybckLo)
        self.ControlsandData.addLayout(self.MotSpd_DatLayout)
        self.Comm_Console.addLayout(self.ControlsandData)
        self.Comm_Console.setStretch(0, 2)
        self.Comm_Console.setStretch(1, 10)
        self.Comm_Console.setStretch(2, 3)
        Comm_Window.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Comm_Window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 991, 19))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        Comm_Window.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(Comm_Window)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        Comm_Window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(Comm_Window)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        Comm_Window.setStatusBar(self.statusBar)

        self.retranslateUi(Comm_Window)
        QtCore.QMetaObject.connectSlotsByName(Comm_Window)

    def retranslateUi(self, Comm_Window):
        Comm_Window.setWindowTitle(_translate("Comm_Window", "Comm_Window", None))
        self.WheelBotComm.setText(_translate("Comm_Window", "WheelBot Communication System 1.0", None))
        self.label.setText(_translate("Comm_Window", "Port:", None))
        self.Connect_Btn.setText(_translate("Comm_Window", "Connect", None))
        self.Disconnect_Btn.setText(_translate("Comm_Window", "Disconnect", None))
        self.Headin_Plt.setText(_translate("Comm_Window", "Heading Plot", None))
        self.PId_Loop_Gain.setText(_translate("Comm_Window", "PID Loop Gains", None))
        self.SendCmds_checkBox.setText(_translate("Comm_Window", "Send Commands", None))
        self.K_plabel.setText(_translate("Comm_Window", "K_p:", None))
        self.kp_val.setText(_translate("Comm_Window", "val", None))
        self.K_iLabel.setText(_translate("Comm_Window", "K_i:", None))
        self.ki_val.setText(_translate("Comm_Window", "val", None))
        self.K_dLabel.setText(_translate("Comm_Window", "K_d:", None))
        self.kd_val.setText(_translate("Comm_Window", "val", None))
        self.Rotat_PWM.setText(_translate("Comm_Window", "Rotational PWM command", None))
        self.Motor_Speed.setText(_translate("Comm_Window", "Motor Speed (rad/s)", None))
        self.LMotLbl.setText(_translate("Comm_Window", "L:", None))
        self.Lft_Motor_Speed.setText(_translate("Comm_Window", "val", None))
        self.RMotLbl.setText(_translate("Comm_Window", "R:", None))
        self.Rgt_Motor_Speed.setText(_translate("Comm_Window", "val", None))
        self.Load_Data.setText(_translate("Comm_Window", "Load Data File", None))
        self.Load_Btn.setText(_translate("Comm_Window", "Load", None))
        self.Record_Btn.setText(_translate("Comm_Window", "Record", None))
        self.Playback_Btn.setText(_translate("Comm_Window", "Playback", None))

